### PR TITLE
增加中文版的文档

### PR DESCRIPTION
**Pull request by xutongle**
增加中文版的文档，持续翻译中！

### CODE REVIEW

**Comment by ovr** [comment]
@racklin
I think you can help to review this?

**Comment by ovr** [comment]
ping @andresgutierrez @phalcon

**Comment by racklin** [comment]
@ovr Sure! I can review Chinese Docs for Zephir Lang .
Sorry for lately reply , i have been business trip to Vladivostok  one year.

**Comment by ovr** [comment]
@racklin 
Not a problem, Vladivostok is an amazing city ^_^

**Comment by racklin** [comment]
@ovr хорошо.  Now, i have learned some Russian language. :+1:

**Pull request merged**
