### PR TITLE
Reduce duplicate code

### PR DESCRIPTION
**Pull request by flip111**

### CODE REVIEW

**Comment by flip111** [comment]
Pr not welcome?

**Comment by sergeyklay** [comment]
Pull requests are always welcome! Could you please open a new one with changes for all languages.

**Comment by flip111** [comment]
What do you mean all languages?

**Comment by sergeyklay** [comment]
* https://github.com/phalcon/zephir-docs/tree/master/en
* https://github.com/phalcon/zephir-docs/tree/master/ru
* https://github.com/phalcon/zephir-docs/tree/master/zh

**Pull request closed without merging**
